AllCops:
  TargetRubyVersion: 2.7.4
  NewCops: enable
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 1000

Metrics/ModuleLength:
  Max: 1000

Layout/LineLength:
  Max: 300

Metrics/ClassLength:
  Max: 2000

Metrics/AbcSize:
  Max: 90

Metrics/BlockLength:
  Max: 45

Metrics/PerceivedComplexity:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 30

Style/NumericLiteralPrefix:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ParameterLists:
  Max: 7

Style/RaiseArgs:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false